[build]
  command = "npx prisma generate && npm run build"
  publish = "build"

[functions]
  node_bundler = "esbuild"


[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"